#!/usr/bin/env bash
# HiveOS run script for xmrig-tari custom miner v10
# Uses --config to force config.json loading (contains explicit thread profiles)

SCRIPT_VERSION="tari25"
EXPECTED_BIN_SIZE=0  # 0 = skip check; CI sets this during build

[[ -z $CUSTOM_MINER ]] && CUSTOM_MINER="xmrig"
[[ -z $CUSTOM_LOG_BASENAME ]] && CUSTOM_LOG_BASENAME="/var/log/miner/custom/xmrig"

MINER_DIR="/hive/miners/custom/$CUSTOM_MINER"
MINER_BIN="$MINER_DIR/xmrig"
CONFIG_FILE="$MINER_DIR/config.json"
LOG_FILE="$CUSTOM_LOG_BASENAME.log"

mkdir -p "$(dirname "$LOG_FILE")" 2>/dev/null

# Debug logging
echo "=== h-run.sh $SCRIPT_VERSION started $(date) ===" | tee -a "$LOG_FILE"
echo "MINER_BIN=$MINER_BIN size=$(stat -c%s "$MINER_BIN" 2>/dev/null)" | tee -a "$LOG_FILE"
echo "CPU: $(grep -m1 'model name' /proc/cpuinfo 2>/dev/null | cut -d: -f2)" >> "$LOG_FILE"
echo "Online CPUs: $(cat /sys/devices/system/cpu/online 2>/dev/null)" >> "$LOG_FILE"
echo "nproc: $(nproc 2>/dev/null)" >> "$LOG_FILE"
echo "CUSTOM_URL=$CUSTOM_URL" >> "$LOG_FILE"
echo "CUSTOM_TEMPLATE=$CUSTOM_TEMPLATE" >> "$LOG_FILE"
echo "CUSTOM_USER_CONFIG=$CUSTOM_USER_CONFIG" >> "$LOG_FILE"

# Version check: detect stale binary from HiveOS cache
# The binary must contain our patched options table (has "no-config" string)
if [[ -f "$MINER_BIN" ]]; then
    if ! strings "$MINER_BIN" 2>/dev/null | grep -q "no-config"; then
        echo "WARN: Binary is outdated (missing no-config option). Force re-downloading..." | tee -a "$LOG_FILE"
        DOWNLOAD_URL="https://github.com/JustAResearcher/xmrig-tari/releases/latest/download/xmrig-tari.tar.gz"
        echo "Downloading from $DOWNLOAD_URL" | tee -a "$LOG_FILE"
        cd /tmp
        wget -q --no-check-certificate -O xmrig-tari-update.tar.gz "$DOWNLOAD_URL" 2>>"$LOG_FILE"
        if [[ $? -eq 0 && -f xmrig-tari-update.tar.gz ]]; then
            tar xzf xmrig-tari-update.tar.gz -C "$MINER_DIR" --strip-components=1 2>>"$LOG_FILE"
            chmod +x "$MINER_BIN" 2>/dev/null
            rm -f xmrig-tari-update.tar.gz
            echo "Binary updated. New size: $(stat -c%s "$MINER_BIN" 2>/dev/null)" | tee -a "$LOG_FILE"
        else
            echo "WARN: Download failed, continuing with existing binary" | tee -a "$LOG_FILE"
        fi
        cd "$MINER_DIR"
    fi
fi

# Verify binary
if [[ ! -f "$MINER_BIN" ]]; then
    echo "FATAL: Binary not found: $MINER_BIN" | tee -a "$LOG_FILE"
    sleep 10
    exit 1
fi
chmod +x "$MINER_BIN" 2>/dev/null

# Verify config.json exists (generated by h-config.sh)
if [[ ! -f "$CONFIG_FILE" ]]; then
    echo "WARN: config.json not found, h-config.sh may not have run" >> "$LOG_FILE"
fi

# Quick smoke test
echo "Running smoke test..." >> "$LOG_FILE"
"$MINER_BIN" --version >> "$LOG_FILE" 2>&1
SMOKE_RC=$?
echo "Smoke test exit code: $SMOKE_RC" >> "$LOG_FILE"

if [[ $SMOKE_RC -ne 0 ]]; then
    echo "FATAL: Binary smoke test failed (exit $SMOKE_RC)" | tee -a "$LOG_FILE"
    sleep 10
    exit 1
fi

# Enable 1GB pages if available
if [[ -d /sys/kernel/mm/hugepages/hugepages-1048576kB ]]; then
    _current=$(cat /sys/kernel/mm/hugepages/hugepages-1048576kB/nr_hugepages 2>/dev/null)
    if [[ "$_current" == "0" ]]; then
        echo 4 > /sys/kernel/mm/hugepages/hugepages-1048576kB/nr_hugepages 2>/dev/null
        echo "1GB pages: requested 4" >> "$LOG_FILE"
    fi
fi

# Allocate 2MB hugepages: need 1024 for RandomX dataset (2048MB) + 1 per thread for scratchpads
# On NUMA systems, distribute across nodes for optimal performance
THREADS=$(nproc)
NUMA_NODES=$(lscpu 2>/dev/null | grep "^NUMA node(s):" | awk '{print $NF}')
NUMA_NODES=${NUMA_NODES:-1}
DATASET_PAGES=1040  # 2080MB dataset / 2MB per page
PAGES_NEEDED=$(( (DATASET_PAGES + THREADS) * NUMA_NODES ))
CURRENT_PAGES=$(cat /proc/sys/vm/nr_hugepages 2>/dev/null)
CURRENT_PAGES=${CURRENT_PAGES:-0}

# Check available RAM (leave 4GB free for system)
AVAIL_MB=$(awk '/MemAvailable/ {print int($2/1024)}' /proc/meminfo 2>/dev/null)
AVAIL_MB=${AVAIL_MB:-0}
MAX_PAGES=$(( (AVAIL_MB - 4096) / 2 ))
if [[ $MAX_PAGES -lt 0 ]]; then MAX_PAGES=0; fi

# Cap hugepages to available memory
if [[ $PAGES_NEEDED -gt $MAX_PAGES ]]; then
    # Fall back to 1 dataset + all scratchpads
    PAGES_NEEDED=$(( DATASET_PAGES + THREADS ))
    if [[ $PAGES_NEEDED -gt $MAX_PAGES ]]; then
        PAGES_NEEDED=$MAX_PAGES
    fi
fi

echo "NUMA nodes: $NUMA_NODES, threads: $THREADS, hugepages: current=$CURRENT_PAGES needed=$PAGES_NEEDED" >> "$LOG_FILE"

if [[ $PAGES_NEEDED -gt $CURRENT_PAGES ]]; then
    # Drop caches first to free contiguous memory
    echo 3 > /proc/sys/vm/drop_caches 2>/dev/null
    sleep 1
    echo $PAGES_NEEDED > /proc/sys/vm/nr_hugepages 2>/dev/null
    ACTUAL=$(cat /proc/sys/vm/nr_hugepages 2>/dev/null)
    echo "Hugepages: requested=$PAGES_NEEDED actual=$ACTUAL" >> "$LOG_FILE"
fi

# Load MSR module for RandomX performance boost
modprobe msr 2>/dev/null
echo "MSR module: $(lsmod | grep -c msr) loaded" >> "$LOG_FILE"

# Log the config.json thread profile for diagnostics
if [[ -f "$CONFIG_FILE" ]]; then
    RX_TARI_THREADS=$(python3 -c "
import json,sys
try:
    c=json.load(open('$CONFIG_FILE'))
    t=c.get('cpu',{}).get('rx/tari',[])
    print(f'rx/tari={len(t)} threads, first={t[:3] if t else \"none\"}, last={t[-3:] if t else \"none\"}')
except: print('parse error')
" 2>/dev/null || echo "no python3")
    echo "Config thread profile: $RX_TARI_THREADS" >> "$LOG_FILE"
fi

cd "$MINER_DIR"

# Strip --no-config from CUSTOM_USER_CONFIG
# HiveOS injects --no-config for custom miners. Even though our binary
# handles it, older cached binaries may not. Remove it at the shell level.
CUSTOM_USER_CONFIG=$(echo "$CUSTOM_USER_CONFIG" | sed 's/--no-config//g; s/  */ /g; s/^ *//; s/ *$//')

echo "Launching with --config $CONFIG_FILE (thread profiles in config, no --threads CLI)" >> "$LOG_FILE"
echo "CUSTOM_USER_CONFIG after filter: '$CUSTOM_USER_CONFIG'" >> "$LOG_FILE"

# CRITICAL: Use --config to FORCE config.json loading.
# Without --config, XMRig builds a valid config from CLI args alone
# and NEVER loads config.json, falling back to hwloc auto-detect
# which gives only 48 threads (physical cores) on EPYC instead of 96.
# The config.json has explicit "rx/tari" thread profiles with ALL logical CPUs.
echo "=== Starting XMRig at $(date) ===" | tee -a "$LOG_FILE"
"$MINER_BIN" \
    --no-color \
    --config "$CONFIG_FILE" \
    --donate-level 0 \
    --randomx-1gb-pages \
    --log-file "$LOG_FILE" \
    --print-time 10 \
    $CUSTOM_USER_CONFIG

MINER_EXIT=$?
echo "=== MINER EXITED with code $MINER_EXIT at $(date) ===" | tee -a "$LOG_FILE"

# If miner exited unexpectedly, give HiveOS watchdog time to see the error
if [[ $MINER_EXIT -ne 0 ]]; then
    echo "Binary: $(file "$MINER_BIN" 2>/dev/null)" >> "$LOG_FILE"
    echo "Last 20 lines of log:" >> "$LOG_FILE"
    tail -20 "$LOG_FILE" >> "$LOG_FILE" 2>/dev/null
    sleep 15
fi
exit $MINER_EXIT
